"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"

// Inner tooltip - detailed explanation for each variable
function DetailedTooltip({ 
  variable, 
  name, 
  description, 
  isVisible 
}: { 
  variable: string
  name: string
  description: string
  isVisible: boolean
}) {
  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: 8, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 8, scale: 0.95 }}
          transition={{ duration: 0.2, ease: "easeOut" }}
          className="absolute top-full left-1/2 -translate-x-1/2 mt-4 z-[60] pointer-events-none"
        >
          <div className="bg-card/95 backdrop-blur-sm border border-accent/30 rounded-lg p-4 shadow-2xl min-w-[240px] max-w-[300px]">
            {/* Arrow pointing up */}
            <div className="absolute left-1/2 -translate-x-1/2 -top-2 w-4 h-4 bg-card/95 border-l border-t border-accent/30 rotate-45" />
            
            {/* Content */}
            <div className="relative space-y-3">
              <div className="flex items-center gap-3">
                <span className="text-3xl font-mono font-bold text-accent">{variable}</span>
                <div>
                  <span className="text-sm font-semibold text-foreground">{name}</span>
                  {variable === "A" && (
                    <span className="block text-xs text-accent">*Human in the Loop</span>
                  )}
                </div>
              </div>
              <div className="h-px bg-border" />
              <p className="text-xs text-muted-foreground leading-relaxed">{description}</p>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// Outer tooltip - overview of all variables
function OverviewTooltip({ isVisible }: { isVisible: boolean }) {
  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          transition={{ duration: 0.25, ease: "easeOut" }}
          className="absolute bottom-full left-1/2 -translate-x-1/2 mb-6 z-50 pointer-events-none"
        >
          <div className="bg-card/95 backdrop-blur-sm border border-border rounded-lg p-5 shadow-2xl min-w-[280px]">
            {/* Arrow pointing down */}
            <div className="absolute left-1/2 -translate-x-1/2 -bottom-2 w-4 h-4 bg-card/95 border-r border-b border-border rotate-45" />
            
            {/* Content */}
            <div className="relative space-y-4">
              <div className="text-center">
                <h3 className="text-sm font-semibold text-foreground">FDIA Equation</h3>
                <p className="text-xs text-muted-foreground mt-1">Hover each variable for details</p>
              </div>
              
              <div className="h-px bg-border" />
              
              <div className="grid grid-cols-2 gap-3">
                <div className="flex items-center gap-2">
                  <span className="text-lg font-mono font-bold text-foreground">F</span>
                  <span className="text-xs text-muted-foreground">= Future</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-lg font-mono font-bold text-accent">D</span>
                  <span className="text-xs text-muted-foreground">= Data</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-lg font-mono font-bold text-accent">I</span>
                  <span className="text-xs text-muted-foreground">= Intent</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-lg font-mono font-bold text-foreground">A</span>
                  <span className="text-xs text-muted-foreground">= Architect*</span>
                </div>
              </div>
              
              <p className="text-xs text-center text-muted-foreground/70">*Human in the Loop</p>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

export function FDIAEquation() {
  const [hoveredVar, setHoveredVar] = useState<string | null>(null)
  const [isHoveringEquation, setIsHoveringEquation] = useState(false)

  const variables = {
    F: {
      name: "Future",
      description: "The outcome or result generated by the system. Represents the intelligent output shaped by data, intent, and human guidance. F is determined by the exponential relationship between Data and Intent, multiplied by the Architect's oversight.",
    },
    D: {
      name: "Data",
      description: "Raw information and context fed into the system. The foundation upon which intelligence is built. Data alone is inert - it requires Intent to unlock its potential.",
    },
    I: {
      name: "Intent",
      description: "The purpose and goal behind the operation. Intent acts as an exponent, elevating data exponentially. It transforms raw information into meaningful, directed action toward specific outcomes.",
    },
    A: {
      name: "Architect",
      description: "Human-in-the-loop oversight and guidance. The Architect multiplies the AI output, ensuring alignment with real-world needs, ethical considerations, and strategic goals. Without human guidance, AI lacks direction.",
    },
  }

  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.12,
        delayChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { opacity: 0, y: 30, scale: 0.8 },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        type: "spring" as const,
        stiffness: 120,
        damping: 12,
      },
    },
  }

  const glowVariants = {
    initial: { scale: 1, opacity: 0.15 },
    animate: {
      scale: [1, 1.15, 1],
      opacity: [0.15, 0.3, 0.15],
      transition: {
        duration: 4,
        repeat: Infinity,
        ease: "easeInOut" as const,
      },
    },
  }

  // Check if any individual variable is hovered
  const showOverview = isHoveringEquation && !hoveredVar

  return (
    <div className="relative flex flex-col items-center justify-center py-12 md:py-16">
      {/* Animated glow background */}
      <motion.div
        variants={glowVariants}
        initial="initial"
        animate="animate"
        className="absolute blur-3xl bg-accent/20 rounded-full pointer-events-none"
        style={{ width: "100%", maxWidth: "600px", height: "300px" }}
      />

      {/* Equation Wrapper - triggers outer tooltip */}
      <div
        className="relative"
        onMouseEnter={() => setIsHoveringEquation(true)}
        onMouseLeave={() => {
          setIsHoveringEquation(false)
          setHoveredVar(null)
        }}
      >
        {/* Overview Tooltip (Outer Layer) */}
        <OverviewTooltip isVisible={showOverview} />

        {/* Main Equation Container */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="relative flex items-baseline font-mono font-bold select-none px-4"
        >
          {/* F */}
          <motion.div variants={itemVariants} className="relative">
            <motion.span
              className={`text-5xl sm:text-6xl md:text-7xl lg:text-8xl cursor-pointer transition-all duration-300 ${
                hoveredVar === "F" ? "text-accent" : "text-foreground"
              }`}
              onMouseEnter={() => setHoveredVar("F")}
              onMouseLeave={() => setHoveredVar(null)}
              whileHover={{ scale: 1.1 }}
            >
              F
            </motion.span>
            <DetailedTooltip
              variable="F"
              name={variables.F.name}
              description={variables.F.description}
              isVisible={hoveredVar === "F"}
            />
          </motion.div>

          {/* = */}
          <motion.span
            variants={itemVariants}
            className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl text-muted-foreground mx-3 md:mx-5"
          >
            =
          </motion.span>

          {/* ( */}
          <motion.span
            variants={itemVariants}
            className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-muted-foreground/50"
          >
            (
          </motion.span>

          {/* D^I */}
          <motion.div variants={itemVariants} className="relative flex items-start">
            {/* D */}
            <div className="relative">
              <motion.span
                className={`text-5xl sm:text-6xl md:text-7xl lg:text-8xl cursor-pointer transition-all duration-300 ${
                  hoveredVar === "D" ? "brightness-125" : ""
                } text-accent`}
                onMouseEnter={() => setHoveredVar("D")}
                onMouseLeave={() => setHoveredVar(null)}
                whileHover={{ scale: 1.1 }}
              >
                D
              </motion.span>
              <DetailedTooltip
                variable="D"
                name={variables.D.name}
                description={variables.D.description}
                isVisible={hoveredVar === "D"}
              />
            </div>

            {/* I (superscript) */}
            <div className="relative -ml-1">
              <motion.span
                className={`text-2xl sm:text-3xl md:text-4xl lg:text-5xl cursor-pointer transition-all duration-300 inline-block align-super ${
                  hoveredVar === "I" ? "brightness-125" : ""
                } text-accent`}
                style={{ marginTop: "-1.5rem" }}
                onMouseEnter={() => setHoveredVar("I")}
                onMouseLeave={() => setHoveredVar(null)}
                whileHover={{ scale: 1.15 }}
              >
                I
              </motion.span>
              <DetailedTooltip
                variable="I"
                name={variables.I.name}
                description={variables.I.description}
                isVisible={hoveredVar === "I"}
              />
            </div>
          </motion.div>

          {/* ) */}
          <motion.span
            variants={itemVariants}
            className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-muted-foreground/50"
          >
            )
          </motion.span>

          {/* x */}
          <motion.span
            variants={itemVariants}
            className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl text-muted-foreground mx-3 md:mx-5"
          >
            x
          </motion.span>

          {/* A */}
          <motion.div variants={itemVariants} className="relative">
            <motion.span
              className={`text-5xl sm:text-6xl md:text-7xl lg:text-8xl cursor-pointer transition-all duration-300 ${
                hoveredVar === "A" ? "text-accent" : "text-foreground"
              }`}
              onMouseEnter={() => setHoveredVar("A")}
              onMouseLeave={() => setHoveredVar(null)}
              whileHover={{ scale: 1.1 }}
            >
              A
            </motion.span>
            <DetailedTooltip
              variable="A"
              name={variables.A.name}
              description={variables.A.description}
              isVisible={hoveredVar === "A"}
            />
          </motion.div>
        </motion.div>
      </div>

      {/* Equation Label */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.2, duration: 0.5 }}
        className="mt-8"
      >
        <span className="text-xs font-mono text-muted-foreground tracking-widest uppercase">
          The FDIA Equation
        </span>
      </motion.div>
    </div>
  )
}
