export const pixelIcons = {
  brain: "/images/pixel/cleaned/brain.webp",
  shield: "/images/pixel/cleaned/shield.webp",
  network: "/images/pixel/cleaned/network.webp",
  architecture: "/images/pixel/cleaned/architecture.webp",
  genome: "/images/pixel/cleaned/genome.webp",
  jitna: "/images/pixel/cleaned/jitna.webp",
  algorithms: "/images/pixel/cleaned/algorithms.webp",
  rocket: "/images/pixel/cleaned/rocket.webp",
  evidence: "/images/pixel/cleaned/evidence.webp",
  cpu: "/images/pixel/cleaned/cpu.webp",
  database: "/images/pixel/cleaned/database.webp",
  heart: "/images/pixel/cleaned/heart.webp",
  target: "/images/pixel/cleaned/target.webp",
  layers: "/images/pixel/cleaned/layers.webp",
  chart: "/images/pixel/cleaned/chart.webp",
  document: "/images/pixel/cleaned/document.webp",
  formula: "/images/pixel/cleaned/formula.webp",
  map: "/images/pixel/cleaned/map.webp",
  flag: "/images/pixel/cleaned/flag.webp",
} as const