export const pixelIcons = {
  brain: "/images/pixel/8bit-brain-icon-YV3hZvbAaJBXWEMr6T2Tnc.webp",
  shield: "/images/pixel/8bit-shield-icon-MfxsPeu6XRAKST8C3hCmf9.webp",
  network: "/images/pixel/8bit-network-icon-8aUM6KhHFxaYJMNCWLXw5c.webp",
  architecture: "/images/pixel/8bit-architecture-layers.webp",
  genome: "/images/pixel/8bit-genome-dna.webp",
  jitna: "/images/pixel/8bit-jitna-protocol.webp",
  algorithms: "/images/pixel/8bit-algorithm-gears.webp",
  rocket: "/images/pixel/8bit-rocket-icon-oSMB9StjMFt3Nvu8bxaJcw.webp",
  evidence: "/images/pixel/8bit-evidence-book.webp",
  // New colorful V2 icons — added 2026-03-27 & 28
  cpu: "/images/pixel/pixel-v2-cpu.webp",
  database: "/images/pixel/pixel-v2-database.webp",
  heart: "/images/pixel/pixel-v2-heart.webp",
  target: "/images/pixel/pixel-v2-target.webp",
  layers: "/images/pixel/pixel-v2-layers.webp",
  chart: "/images/pixel/pixel-v2-chart.webp",
  document: "/images/pixel/pixel-v2-document.webp",
  formula: "/images/pixel/pixel-v2-formula.webp",
  map: "/images/pixel/pixel-v2-map.webp",
  flag: "/images/pixel/pixel-v2-flag.webp",
} as const