export const pixelIcons = {
  brain: "/images/pixel/8bit-brain-icon-YV3hZvbAaJBXWEMr6T2Tnc.webp",
  shield: "/images/pixel/8bit-shield-icon-MfxsPeu6XRAKST8C3hCmf9.webp",
  network: "/images/pixel/8bit-network-icon-8aUM6KhHFxaYJMNCWLXw5c.webp",
  architecture: "/images/pixel/8bit-architecture-layers.webp",
  genome: "/images/pixel/8bit-genome-dna.webp",
  jitna: "/images/pixel/8bit-jitna-protocol.webp",
  algorithms: "/images/pixel/8bit-algorithm-gears.webp",
  rocket: "/images/pixel/8bit-rocket-icon-oSMB9StjMFt3Nvu8bxaJcw.webp",
  evidence: "/images/pixel/8bit-evidence-book.webp",
  // New icons — added 2026-03-27
  cpu: "/images/pixel/8bit-cpu-chip.png",
  database: "/images/pixel/8bit-database.png",
  heart: "/images/pixel/8bit-heart.png",
  target: "/images/pixel/8bit-target.png",
  layers: "/images/pixel/8bit-layers.png",
  chart: "/images/pixel/8bit-chart.png",
  document: "/images/pixel/8bit-document.png",
  formula: "/images/pixel/8bit-formula.png",
  map: "/images/pixel/8bit-map.png",
  flag: "/images/pixel/8bit-flag.png",
} as const