export const SITE_URL = "https://rctlabs.co"
export const SITE_NAME = "RCT Labs"
export const SITE_DESCRIPTION = "Enterprise AI architecture and verification platform built around FDIA, JITNA, SignedAI, and staged deployment evidence."
export const SITE_OG_IMAGE = `${SITE_URL}/opengraph-image`
export const SITE_VERSION = "2026.04 Snapshot"
export const SITE_TEST_COUNT = 4849 // Enterprise full suite (private)
export const SITE_PUBLIC_SDK_VERSION = "1.0.1a0"
export const SITE_PUBLIC_SDK_TESTS = 591 // Public SDK full suite: 591 passed · 0 failed · 89% coverage (rctlabs/rct-platform)
export const SITE_MICROSERVICE_COUNT = 62
export const SITE_ALGORITHM_COUNT = 41
export const SITE_LAYER_COUNT = 10 // Product layers L1-L10; L11 = CI/CD pipeline layer (internal only)
export const SITE_HEXACORE_COUNT = 7
export const SITE_CONSENSUS_MODELS = 7 // HexaCore roster: 3W (Claude/Gemini/Grok) + 3E (Kimi/MiniMax/DeepSeek) + 1TH (Typhoon); mirrors SITE_HEXACORE_COUNT
export const SITE_UPTIME = "99.98% SLA"
export const SITE_HALLUCINATION_RATE = "0.3% benchmark"

export const SOCIAL_LINKS = {
  github: "https://github.com/rctlabs",
  platformGithub: "https://github.com/rctlabs/rct-platform",
  linkedin: "https://linkedin.com/company/rctlabs",
  twitter: "https://twitter.com/rctlabs",
  discord: "https://discord.gg/rctlabs",
  twitterHandle: "@rctlabs",
} as const

export const PUBLIC_ROUTE_PRIORITIES: Record<string, number> = {
  "/": 1,
  "/pricing": 0.95,
  "/solutions": 0.9,
  "/products": 0.9,
  "/about": 0.85,
  "/company": 0.85,
  "/core-systems": 0.85,
  "/architecture": 0.8,
  "/research": 0.8,
  "/blog": 0.8,
  "/evaluation": 0.76,
  "/evaluation/enterprise-ai-governance-vs-generic-copilots": 0.7,
  "/evaluation/enterprise-ai-memory-vs-large-context-windows": 0.7,
  "/evaluation/dynamic-ai-routing-vs-static-orchestration": 0.7,
  "/evaluation/build-vs-buy-governed-ai-systems": 0.7,
  "/evaluation/enterprise-ai-platform-evaluation-checklist": 0.69,
  "/methodology": 0.74,
  "/benchmark-summary": 0.74,
  "/thailand-enterprise-trust": 0.73,
  "/glossary": 0.72,
  "/editorial-policy": 0.72,
  "/roadmap": 0.75,
  "/contact": 0.75,
  "/docs": 0.7,
  "/press": 0.77,
  "/authors": 0.72,
  "/authors/ittirit-saengow": 0.78,
  "/authors/rct-research-desk": 0.65,
  "/case-studies/stardew-valley": 0.71,
  "/compare": 0.75,
  "/compare/constitutional-ai-vs-rag": 0.75,
  "/compare/rct-labs-vs-llm-apis": 0.75,
  "/compare/verification-vs-prompt-engineering": 0.75,
  "/compare/rctdb-vs-vector-databases": 0.75,
  "/solutions/regional-ai": 0.78,
  "/technology/constitutional-ai": 0.78,
  "/technology/jitna": 0.78,
  "/technology/rct-7": 0.78,
  "/technology/rct-7-thinking": 0.78,
  "/philosophy": 0.72,
  "/philosophy/fdia": 0.74,
  "/philosophy/jitna": 0.73,
  "/philosophy/rct-7": 0.72,
  "/philosophy/intent-os": 0.70,
  "/philosophy/vision": 0.74,
  "/philosophy/values": 0.72,
  "/philosophy/ethics": 0.72,
  "/philosophy/approach": 0.72,
  "/philosophy/impact": 0.71,
  "/open-protocol": 0.76,
  "/genome": 0.80,
  "/genome/architect": 0.80,
  "/genome/artent": 0.80,
  "/genome/jitna": 0.82,
  "/genome/codex": 0.80,
  "/genome/signed-ai": 0.81,
  "/genome/vault": 0.78,
  "/genome/rct-7": 0.80,
  "/algorithms": 0.79,
  "/fdia": 0.78,
  "/protocols": 0.77,
  // Entity pages — high-value original knowledge pages for AIO/entity search
  "/entity/fdia-equation": 0.82,
  "/entity/jitna-protocol": 0.82,
  "/entity/rct-kernel": 0.80,
  "/entity/intent-profiles": 0.78,
  "/entity/governance-layer": 0.78,
  "/entity/memory-architecture": 0.78,
  // High-traffic routes without explicit priority (previously falling back to 0.65)
  "/benchmark": 0.78,
  "/whitepaper": 0.77,
  "/whitepaper/fdia-equation-v2": 0.82,
  "/whitepaper/jitna-rfc-001": 0.82,
  "/demo/fdia": 0.75,
  "/faq": 0.73,
  "/changelog": 0.72,
  "/use-cases": 0.70,
  "/integration": 0.70,
  "/platform": 0.68,
  "/community": 0.68,
  "/community/events": 0.62,
  "/community/forums": 0.62,
  "/community/members": 0.60,
}

export const PUBLIC_ROUTES = [
  "/",
  "/about",
  "/pricing",
  "/products",
  "/products/rctlabs",
  "/products/artent-ai",
  "/products/signed-ai",
  "/solutions",
  "/solutions/ai-hallucination-prevention",
  "/solutions/enterprise-ai-memory",
  "/solutions/dynamic-ai-routing",
  "/solutions/regional-ai",
  "/core-systems",
  "/architecture",
  "/genome",
  "/genome/architect",
  "/genome/artent",
  "/genome/jitna",
  "/genome/codex",
  "/genome/signed-ai",
  "/genome/vault",
  "/genome/rct-7",
  "/fdia",
  "/algorithms",
  "/benchmark",
  "/integration",
  "/protocols",
  "/protocols/jitna-rfc-001",
  "/protocols/fdia-equation",
  "/protocols/rct-7-mental-model",
  "/technology/constitutional-ai",
  "/technology/jitna",
  "/technology/rct-7",
  "/technology/rct-7-thinking",
  "/whitepaper",
  "/whitepaper/fdia-equation-v2",
  "/whitepaper/jitna-rfc-001",
  "/demo/fdia",
  "/use-cases",
  "/faq",
  "/changelog",
  "/company",
  "/company/careers",
  "/company/partners",
  "/research",
  "/docs",
  "/platform",
  "/community",
  "/community/events",
  "/community/forums",
  "/community/members",
  "/blog",
  "/methodology",
  "/editorial-policy",
  "/glossary",
  "/evaluation",
  "/evaluation/enterprise-ai-governance-vs-generic-copilots",
  "/evaluation/enterprise-ai-memory-vs-large-context-windows",
  "/evaluation/dynamic-ai-routing-vs-static-orchestration",
  "/evaluation/build-vs-buy-governed-ai-systems",
  "/evaluation/enterprise-ai-platform-evaluation-checklist",
  "/benchmark-summary",
  "/thailand-enterprise-trust",
  "/contact",
  "/press",
  "/privacy",
  "/terms",
  "/roadmap",
  "/authors",
  "/authors/ittirit-saengow",
  "/authors/rct-research-desk",
  "/case-studies/stardew-valley",
  "/compare",
  "/compare/constitutional-ai-vs-rag",
  "/compare/rct-labs-vs-llm-apis",
  "/compare/verification-vs-prompt-engineering",
  "/compare/rctdb-vs-vector-databases",
  "/philosophy",
  "/philosophy/fdia",
  "/philosophy/jitna",
  "/philosophy/rct-7",
  "/philosophy/intent-os",
  "/philosophy/values",
  "/philosophy/vision",
  "/philosophy/ethics",
  "/philosophy/approach",
  "/philosophy/impact",
  "/open-protocol",
  // Entity pages — knowledge graph nodes for AI-optimized search
  "/entity/fdia-equation",
  "/entity/jitna-protocol",
  "/entity/rct-kernel",
  "/entity/intent-profiles",
  "/entity/governance-layer",
  "/entity/memory-architecture",
] as const

export const NOINDEX_ROUTE_PREFIXES = [
  "/admin",
  "/analytics",
  "/monitor",
  "/owner",
  "/studio",
  "/test-console",
  "/websocket",
  "/api",
] as const