export const SITE_URL = "https://rctlabs.co"
export const SITE_NAME = "RCT Labs"
export const SITE_DESCRIPTION = "Enterprise AI architecture and verification platform built around FDIA, JITNA, SignedAI, and staged deployment evidence."
export const SITE_OG_IMAGE = `${SITE_URL}/opengraph-image`
export const SITE_VERSION = "2026.03 Snapshot"
export const SITE_TEST_COUNT = 4849
export const SITE_MICROSERVICE_COUNT = 62
export const SITE_ALGORITHM_COUNT = 41
export const SITE_LAYER_COUNT = 10
export const SITE_HEXACORE_COUNT = 7
export const SITE_CONSENSUS_MODELS = 3
export const SITE_UPTIME = "99.98% SLA"
export const SITE_HALLUCINATION_RATE = "0.3% benchmark"

export const SOCIAL_LINKS = {
  github: "https://github.com/rctlabs",
  linkedin: "https://linkedin.com/company/rctlabs",
  twitter: "https://twitter.com/rctlabs",
  discord: "https://discord.gg/rctlabs",
  twitterHandle: "@rctlabs",
} as const

export const PUBLIC_ROUTE_PRIORITIES: Record<string, number> = {
  "/": 1,
  "/pricing": 0.95,
  "/solutions": 0.9,
  "/products": 0.9,
  "/about": 0.85,
  "/company": 0.85,
  "/core-systems": 0.85,
  "/architecture": 0.8,
  "/research": 0.8,
  "/blog": 0.8,
  "/evaluation": 0.76,
  "/evaluation/enterprise-ai-governance-vs-generic-copilots": 0.7,
  "/evaluation/enterprise-ai-memory-vs-large-context-windows": 0.7,
  "/evaluation/dynamic-ai-routing-vs-static-orchestration": 0.7,
  "/evaluation/build-vs-buy-governed-ai-systems": 0.7,
  "/evaluation/enterprise-ai-platform-evaluation-checklist": 0.69,
  "/methodology": 0.74,
  "/benchmark-summary": 0.74,
  "/thailand-enterprise-trust": 0.73,
  "/glossary": 0.72,
  "/editorial-policy": 0.72,
  "/roadmap": 0.75,
  "/contact": 0.75,
  "/docs": 0.7,
  "/press": 0.77,
  "/authors": 0.72,
  "/authors/ittirit-saengow": 0.78,
  "/authors/rct-research-desk": 0.65,
  "/case-studies/stardew-valley": 0.71,
  "/compare": 0.75,
  "/compare/constitutional-ai-vs-rag": 0.75,
  "/compare/rct-labs-vs-llm-apis": 0.75,
  "/compare/verification-vs-prompt-engineering": 0.75,
  "/compare/rctdb-vs-vector-databases": 0.75,
}

export const PUBLIC_ROUTES = [
  "/",
  "/about",
  "/pricing",
  "/products",
  "/products/rctlabs",
  "/products/artent-ai",
  "/products/signed-ai",
  "/solutions",
  "/solutions/ai-hallucination-prevention",
  "/solutions/enterprise-ai-memory",
  "/solutions/dynamic-ai-routing",
  "/core-systems",
  "/architecture",
  "/genome",
  "/fdia",
  "/algorithms",
  "/benchmark",
  "/integration",
  "/protocols",
  "/protocols/jitna-rfc-001",
  "/protocols/fdia-equation",
  "/protocols/rct-7-mental-model",
  "/whitepaper",
  "/use-cases",
  "/faq",
  "/changelog",
  "/company",
  "/company/careers",
  "/company/partners",
  "/research",
  "/docs",
  "/platform",
  "/community",
  "/blog",
  "/methodology",
  "/editorial-policy",
  "/glossary",
  "/evaluation",
  "/evaluation/enterprise-ai-governance-vs-generic-copilots",
  "/evaluation/enterprise-ai-memory-vs-large-context-windows",
  "/evaluation/dynamic-ai-routing-vs-static-orchestration",
  "/evaluation/build-vs-buy-governed-ai-systems",
  "/evaluation/enterprise-ai-platform-evaluation-checklist",
  "/benchmark-summary",
  "/thailand-enterprise-trust",
  "/contact",
  "/press",
  "/privacy",
  "/terms",
  "/roadmap",
  "/authors",
  "/authors/ittirit-saengow",
  "/authors/rct-research-desk",
  "/case-studies/stardew-valley",
  "/compare",
  "/compare/constitutional-ai-vs-rag",
  "/compare/rct-labs-vs-llm-apis",
  "/compare/verification-vs-prompt-engineering",
  "/compare/rctdb-vs-vector-databases",
] as const

export const NOINDEX_ROUTE_PREFIXES = [
  "/admin",
  "/analytics",
  "/monitor",
  "/owner",
  "/studio",
  "/test-console",
  "/websocket",
  "/api",
] as const